intersections = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31",
    "32",
    "33",
    "34",
    "35",
    "36",
    "37",
    "38",
    "39"
]

roads = [
    ["1", "2"],
    ["7", "1"],
    ["8", "1"],
    ["11", "1"],
    ["12", "1"],
    ["13", "1"],
    ["22", "1"],
    ["23", "1"],
    ["34", "1"],
    ["35", "1"],
    ["37", "1"],
    ["39", "1"],
    ["7", "2"],
    ["8", "2"],
    ["9", "2"],
    ["11", "2"],
    ["12", "2"],
    ["13", "2"],
    ["22", "2"],
    ["23", "2"],
    ["35", "2"],
    ["36", "2"],
    ["39", "2"],
    ["14", "3"],
    ["15", "3"],
    ["16", "3"],
    ["17", "3"],
    ["18", "3"],
    ["36", "3"],
    ["39", "3"],
    ["17", "4"],
    ["36", "4"],
    ["37", "4"],
    ["39", "4"],
    ["6", "5"],
    ["34", "5"],
    ["35", "5"],
    ["39", "5"],
    ["7", "6"],
    ["35", "6"],
    ["39", "6"],
    ["8", "7"],
    ["9", "7"],
    ["11", "7"],
    ["12", "7"],
    ["13", "7"],
    ["35", "7"],
    ["39", "7"],
    ["9", "8"],
    ["10", "8"],
    ["20", "8"],
    ["21", "8"],
    ["22", "8"],
    ["23", "8"],
    ["24", "8"],
    ["35", "8"],
    ["38", "8"],
    ["39", "8"],
    ["10", "9"],
    ["35", "9"],
    ["36", "9"],
    ["39", "9"],
    ["35", "10"],
    ["36", "10"],
    ["39", "10"],
    ["19", "11"],
    ["35", "11"],
    ["36", "11"],
    ["39", "11"],
    ["19", "12"],
    ["26", "12"],
    ["35", "12"],
    ["36", "12"],
    ["38", "12"],
    ["39", "12"],
    ["35", "13"],
    ["36", "13"],
    ["38", "13"],
    ["39", "13"],
    ["25", "14"],
    ["26", "14"],
    ["27", "14"],
    ["28", "14"],
    ["29", "14"],
    ["36", "14"],
    ["39", "14"],
    ["19", "15"],
    ["25", "15"],
    ["26", "15"],
    ["27", "15"],
    ["28", "15"],
    ["29", "15"],
    ["36", "15"],
    ["39", "15"],
    ["19", "16"],
    ["27", "16"],
    ["36", "16"],
    ["39", "16"],
    ["36", "17"],
    ["39", "17"],
    ["19", "18"],
    ["25", "18"],
    ["26", "18"],
    ["27", "18"],
    ["29", "18"],
    ["32", "18"],
    ["36", "18"],
    ["39", "18"],
    ["33", "19"],
    ["36", "19"],
    ["38", "19"],
    ["39", "19"],
    ["36", "20"],
    ["38", "20"],
    ["39", "20"],
    ["33", "21"],
    ["36", "21"],
    ["38", "21"],
    ["39", "21"],
    ["27", "22"],
    ["28", "22"],
    ["30", "22"],
    ["31", "22"],
    ["32", "22"],
    ["33", "22"],
    ["35", "22"],
    ["36", "22"],
    ["38", "22"],
    ["39", "22"],
    ["30", "23"],
    ["32", "23"],
    ["33", "23"],
    ["35", "23"],
    ["36", "23"],
    ["38", "23"],
    ["39", "23"],
    ["36", "24"],
    ["38", "24"],
    ["39", "24"],
    ["36", "25"],
    ["38", "25"],
    ["39", "25"],
    ["36", "26"],
    ["38", "26"],
    ["39", "26"],
    ["30", "27"],
    ["36", "27"],
    ["38", "27"],
    ["39", "27"],
    ["36", "28"],
    ["38", "28"],
    ["39", "28"],
    ["36", "29"],
    ["38", "29"],
    ["39", "29"],
    ["36", "30"],
    ["38", "30"],
    ["39", "30"],
    ["32", "31"],
    ["36", "31"],
    ["38", "31"],
    ["39", "31"],
    ["36", "32"],
    ["38", "32"],
    ["39", "32"],
    ["36", "33"],
    ["38", "33"],
    ["39", "33"],
    ["37", "34"],
    ["36", "35"],
    ["37", "35"]
]



[[cars]]
speed = 0.04
start = "1"
end   = "2"

[[cars]]
speed = 0.035
start = "1"
end   = "36"

[[cars]]
speed = 0.041
start = "1"
end   = "35"

[[cars]]
speed = 0.02
start = "1"
end   = "10"

[[cars]]
speed = 0.044
start = "1"
end   = "23"

[[cars]]
speed = 0.023
start = "1"
end   = "28"

[[cars]]
speed = 0.042
start = "2"
end   = "21"

[[cars]]
speed = 0.044
start = "2"
end   = "26"

[[cars]]
speed = 0.036
start = "2"
end   = "38"

[[cars]]
speed = 0.026
start = "2"
end   = "25"

[[cars]]
speed = 0.023
start = "2"
end   = "32"

[[cars]]
speed = 0.049
start = "2"
end   = "25"

[[cars]]
speed = 0.042
start = "3"
end   = "22"

[[cars]]
speed = 0.029
start = "3"
end   = "29"

[[cars]]
speed = 0.041
start = "3"
end   = "31"

[[cars]]
speed = 0.042
start = "3"
end   = "29"

[[cars]]
speed = 0.032
start = "3"
end   = "28"

[[cars]]
speed = 0.033
start = "3"
end   = "16"

[[cars]]
speed = 0.02
start = "4"
end   = "3"

[[cars]]
speed = 0.037
start = "4"
end   = "33"

[[cars]]
speed = 0.044
start = "4"
end   = "26"

[[cars]]
speed = 0.026
start = "4"
end   = "5"

[[cars]]
speed = 0.025
start = "4"
end   = "8"

[[cars]]
speed = 0.049
start = "4"
end   = "24"

[[cars]]
speed = 0.024
start = "5"
end   = "20"

[[cars]]
speed = 0.021
start = "5"
end   = "29"

[[cars]]
speed = 0.045
start = "5"
end   = "26"

[[cars]]
speed = 0.034
start = "5"
end   = "29"

[[cars]]
speed = 0.02
start = "5"
end   = "6"

[[cars]]
speed = 0.023
start = "5"
end   = "28"

[[cars]]
speed = 0.033
start = "6"
end   = "12"

[[cars]]
speed = 0.034
start = "6"
end   = "35"

[[cars]]
speed = 0.049
start = "6"
end   = "22"

[[cars]]
speed = 0.046
start = "6"
end   = "23"

[[cars]]
speed = 0.049
start = "6"
end   = "12"

[[cars]]
speed = 0.042
start = "6"
end   = "37"

[[cars]]
speed = 0.04
start = "7"
end   = "39"

[[cars]]
speed = 0.025
start = "7"
end   = "32"

[[cars]]
speed = 0.045
start = "7"
end   = "8"

[[cars]]
speed = 0.041
start = "7"
end   = "11"

[[cars]]
speed = 0.037
start = "7"
end   = "20"

[[cars]]
speed = 0.045
start = "7"
end   = "6"

[[cars]]
speed = 0.022
start = "8"
end   = "23"

[[cars]]
speed = 0.031
start = "8"
end   = "29"

[[cars]]
speed = 0.049
start = "8"
end   = "21"

[[cars]]
speed = 0.041
start = "8"
end   = "9"

[[cars]]
speed = 0.042
start = "8"
end   = "20"

[[cars]]
speed = 0.033
start = "8"
end   = "23"

[[cars]]
speed = 0.046
start = "9"
end   = "5"

[[cars]]
speed = 0.027
start = "9"
end   = "35"

[[cars]]
speed = 0.035
start = "9"
end   = "11"

[[cars]]
speed = 0.049
start = "9"
end   = "31"

[[cars]]
speed = 0.021
start = "9"
end   = "27"

[[cars]]
speed = 0.023
start = "9"
end   = "20"

[[cars]]
speed = 0.042
start = "10"
end   = "26"

[[cars]]
speed = 0.037
start = "10"
end   = "4"

[[cars]]
speed = 0.022
start = "10"
end   = "12"

[[cars]]
speed = 0.033
start = "10"
end   = "34"

[[cars]]
speed = 0.03
start = "10"
end   = "27"

[[cars]]
speed = 0.041
start = "10"
end   = "30"

[[cars]]
speed = 0.024
start = "11"
end   = "12"

[[cars]]
speed = 0.031
start = "11"
end   = "21"

[[cars]]
speed = 0.037
start = "11"
end   = "4"

[[cars]]
speed = 0.04
start = "11"
end   = "25"

[[cars]]
speed = 0.047
start = "11"
end   = "20"

[[cars]]
speed = 0.035
start = "11"
end   = "20"

[[cars]]
speed = 0.04
start = "12"
end   = "34"

[[cars]]
speed = 0.037
start = "12"
end   = "24"

[[cars]]
speed = 0.029
start = "12"
end   = "7"

[[cars]]
speed = 0.043
start = "12"
end   = "8"

[[cars]]
speed = 0.033
start = "12"
end   = "29"

[[cars]]
speed = 0.024
start = "12"
end   = "34"

[[cars]]
speed = 0.047
start = "13"
end   = "22"

[[cars]]
speed = 0.031
start = "13"
end   = "20"

[[cars]]
speed = 0.039
start = "13"
end   = "19"

[[cars]]
speed = 0.037
start = "13"
end   = "22"

[[cars]]
speed = 0.024
start = "13"
end   = "9"

[[cars]]
speed = 0.036
start = "13"
end   = "22"

[[cars]]
speed = 0.026
start = "14"
end   = "9"

[[cars]]
speed = 0.035
start = "14"
end   = "24"

[[cars]]
speed = 0.041
start = "14"
end   = "22"

[[cars]]
speed = 0.043
start = "14"
end   = "16"

[[cars]]
speed = 0.02
start = "14"
end   = "34"

[[cars]]
speed = 0.023
start = "14"
end   = "17"

[[cars]]
speed = 0.02
start = "15"
end   = "14"

[[cars]]
speed = 0.034
start = "15"
end   = "28"

[[cars]]
speed = 0.031
start = "15"
end   = "1"

[[cars]]
speed = 0.04
start = "15"
end   = "31"

[[cars]]
speed = 0.02
start = "15"
end   = "1"

[[cars]]
speed = 0.044
start = "15"
end   = "13"

[[cars]]
speed = 0.02
start = "16"
end   = "39"

[[cars]]
speed = 0.034
start = "16"
end   = "25"

[[cars]]
speed = 0.027
start = "16"
end   = "6"

[[cars]]
speed = 0.043
start = "16"
end   = "37"

[[cars]]
speed = 0.02
start = "16"
end   = "17"

[[cars]]
speed = 0.023
start = "16"
end   = "30"

[[cars]]
speed = 0.044
start = "17"
end   = "18"

[[cars]]
speed = 0.043
start = "17"
end   = "38"

[[cars]]
speed = 0.04
start = "17"
end   = "20"

[[cars]]
speed = 0.04
start = "17"
end   = "5"

[[cars]]
speed = 0.038
start = "17"
end   = "9"

[[cars]]
speed = 0.035
start = "17"
end   = "36"

[[cars]]
speed = 0.029
start = "18"
end   = "5"

[[cars]]
speed = 0.047
start = "18"
end   = "36"

[[cars]]
speed = 0.042
start = "18"
end   = "24"

[[cars]]
speed = 0.02
start = "18"
end   = "1"

[[cars]]
speed = 0.045
start = "18"
end   = "31"

[[cars]]
speed = 0.048
start = "18"
end   = "3"

[[cars]]
speed = 0.042
start = "19"
end   = "22"

[[cars]]
speed = 0.041
start = "19"
end   = "17"

[[cars]]
speed = 0.041
start = "19"
end   = "13"

[[cars]]
speed = 0.042
start = "19"
end   = "11"

[[cars]]
speed = 0.024
start = "19"
end   = "39"

[[cars]]
speed = 0.032
start = "19"
end   = "29"

[[cars]]
speed = 0.046
start = "20"
end   = "3"

[[cars]]
speed = 0.022
start = "20"
end   = "23"

[[cars]]
speed = 0.025
start = "20"
end   = "23"

[[cars]]
speed = 0.039
start = "20"
end   = "33"

[[cars]]
speed = 0.039
start = "20"
end   = "2"

[[cars]]
speed = 0.034
start = "20"
end   = "16"

[[cars]]
speed = 0.043
start = "21"
end   = "18"

[[cars]]
speed = 0.029
start = "21"
end   = "25"

[[cars]]
speed = 0.025
start = "21"
end   = "10"

[[cars]]
speed = 0.038
start = "21"
end   = "20"

[[cars]]
speed = 0.046
start = "21"
end   = "4"

[[cars]]
speed = 0.022
start = "21"
end   = "29"

[[cars]]
speed = 0.048
start = "22"
end   = "12"

[[cars]]
speed = 0.026
start = "22"
end   = "4"

[[cars]]
speed = 0.045
start = "22"
end   = "15"

[[cars]]
speed = 0.029
start = "22"
end   = "14"

[[cars]]
speed = 0.038
start = "22"
end   = "1"

[[cars]]
speed = 0.045
start = "22"
end   = "7"

[[cars]]
speed = 0.044
start = "23"
end   = "8"

[[cars]]
speed = 0.039
start = "23"
end   = "22"

[[cars]]
speed = 0.049
start = "23"
end   = "35"

[[cars]]
speed = 0.049
start = "23"
end   = "12"

[[cars]]
speed = 0.032
start = "23"
end   = "25"

[[cars]]
speed = 0.048
start = "23"
end   = "27"

[[cars]]
speed = 0.025
start = "24"
end   = "17"

[[cars]]
speed = 0.042
start = "24"
end   = "21"

[[cars]]
speed = 0.047
start = "24"
end   = "22"

[[cars]]
speed = 0.039
start = "24"
end   = "33"

[[cars]]
speed = 0.025
start = "24"
end   = "11"

[[cars]]
speed = 0.03
start = "24"
end   = "27"

[[cars]]
speed = 0.039
start = "25"
end   = "18"

[[cars]]
speed = 0.029
start = "25"
end   = "27"

[[cars]]
speed = 0.028
start = "25"
end   = "35"

[[cars]]
speed = 0.046
start = "25"
end   = "3"

[[cars]]
speed = 0.039
start = "25"
end   = "27"

[[cars]]
speed = 0.034
start = "25"
end   = "11"

[[cars]]
speed = 0.042
start = "26"
end   = "31"

[[cars]]
speed = 0.041
start = "26"
end   = "31"

[[cars]]
speed = 0.026
start = "26"
end   = "10"

[[cars]]
speed = 0.042
start = "26"
end   = "28"

[[cars]]
speed = 0.036
start = "26"
end   = "34"

[[cars]]
speed = 0.042
start = "26"
end   = "13"

[[cars]]
speed = 0.038
start = "27"
end   = "20"

[[cars]]
speed = 0.041
start = "27"
end   = "7"

[[cars]]
speed = 0.046
start = "27"
end   = "18"

[[cars]]
speed = 0.036
start = "27"
end   = "31"

[[cars]]
speed = 0.036
start = "27"
end   = "19"

[[cars]]
speed = 0.045
start = "27"
end   = "36"

[[cars]]
speed = 0.041
start = "28"
end   = "31"

[[cars]]
speed = 0.028
start = "28"
end   = "29"

[[cars]]
speed = 0.036
start = "28"
end   = "14"

[[cars]]
speed = 0.028
start = "28"
end   = "20"

[[cars]]
speed = 0.025
start = "28"
end   = "32"

[[cars]]
speed = 0.035
start = "28"
end   = "38"

[[cars]]
speed = 0.022
start = "29"
end   = "3"

[[cars]]
speed = 0.025
start = "29"
end   = "25"

[[cars]]
speed = 0.021
start = "29"
end   = "19"

[[cars]]
speed = 0.042
start = "29"
end   = "21"

[[cars]]
speed = 0.029
start = "29"
end   = "31"

[[cars]]
speed = 0.028
start = "29"
end   = "7"

[[cars]]
speed = 0.02
start = "30"
end   = "18"

[[cars]]
speed = 0.038
start = "30"
end   = "29"

[[cars]]
speed = 0.024
start = "30"
end   = "3"

[[cars]]
speed = 0.027
start = "30"
end   = "18"

[[cars]]
speed = 0.029
start = "30"
end   = "29"

[[cars]]
speed = 0.022
start = "30"
end   = "12"

[[cars]]
speed = 0.035
start = "31"
end   = "4"

[[cars]]
speed = 0.02
start = "31"
end   = "17"

[[cars]]
speed = 0.04
start = "31"
end   = "32"

[[cars]]
speed = 0.036
start = "31"
end   = "32"

[[cars]]
speed = 0.033
start = "31"
end   = "33"

[[cars]]
speed = 0.039
start = "31"
end   = "4"

[[cars]]
speed = 0.047
start = "32"
end   = "27"

[[cars]]
speed = 0.037
start = "32"
end   = "8"

[[cars]]
speed = 0.028
start = "32"
end   = "22"

[[cars]]
speed = 0.044
start = "32"
end   = "28"

[[cars]]
speed = 0.025
start = "32"
end   = "12"

[[cars]]
speed = 0.042
start = "32"
end   = "6"

[[cars]]
speed = 0.038
start = "33"
end   = "5"

[[cars]]
speed = 0.038
start = "33"
end   = "3"

[[cars]]
speed = 0.044
start = "33"
end   = "31"

[[cars]]
speed = 0.022
start = "33"
end   = "9"

[[cars]]
speed = 0.04
start = "33"
end   = "18"

[[cars]]
speed = 0.035
start = "33"
end   = "4"

[[cars]]
speed = 0.046
start = "34"
end   = "36"

[[cars]]
speed = 0.029
start = "34"
end   = "32"

[[cars]]
speed = 0.031
start = "34"
end   = "13"

[[cars]]
speed = 0.036
start = "34"
end   = "39"

[[cars]]
speed = 0.023
start = "34"
end   = "12"

[[cars]]
speed = 0.035
start = "34"
end   = "25"

[[cars]]
speed = 0.036
start = "35"
end   = "9"

[[cars]]
speed = 0.021
start = "35"
end   = "2"

[[cars]]
speed = 0.024
start = "35"
end   = "18"

[[cars]]
speed = 0.028
start = "35"
end   = "20"

[[cars]]
speed = 0.044
start = "35"
end   = "25"

[[cars]]
speed = 0.03
start = "35"
end   = "20"

[[cars]]
speed = 0.043
start = "36"
end   = "12"

[[cars]]
speed = 0.046
start = "36"
end   = "24"

[[cars]]
speed = 0.03
start = "36"
end   = "13"

[[cars]]
speed = 0.029
start = "36"
end   = "32"

[[cars]]
speed = 0.025
start = "36"
end   = "34"

[[cars]]
speed = 0.044
start = "36"
end   = "2"

[[cars]]
speed = 0.039
start = "37"
end   = "27"

[[cars]]
speed = 0.04
start = "37"
end   = "3"

[[cars]]
speed = 0.039
start = "37"
end   = "1"

[[cars]]
speed = 0.022
start = "37"
end   = "39"

[[cars]]
speed = 0.02
start = "37"
end   = "8"

[[cars]]
speed = 0.027
start = "37"
end   = "21"

[[cars]]
speed = 0.028
start = "38"
end   = "6"

[[cars]]
speed = 0.044
start = "38"
end   = "30"

[[cars]]
speed = 0.024
start = "38"
end   = "30"

[[cars]]
speed = 0.047
start = "38"
end   = "34"

[[cars]]
speed = 0.044
start = "38"
end   = "5"

[[cars]]
speed = 0.028
start = "38"
end   = "30"

[[cars]]
speed = 0.028
start = "39"
end   = "1"

[[cars]]
speed = 0.046
start = "39"
end   = "22"

[[cars]]
speed = 0.045
start = "39"
end   = "23"

[[cars]]
speed = 0.028
start = "39"
end   = "26"

[[cars]]
speed = 0.024
start = "39"
end   = "6"

[[cars]]
speed = 0.043
start = "39"
end   = "33"
