intersections = [
    "0", 
    "1", 
    "2",
    "3",
    "4",
    "5"
]

roads = [ 
      ["0", "1"],
      ["1", "2"],
      ["2", "3"],
      ["3", "4"],
      ["4", "5"],
      ["5", "0"],
]

[[cars]]
speed = 0.02
start = "0"
end   = "5"

[[cars]]
speed = 0.03
start = "0"
end   = "5"

[[cars]]
speed = 0.04
start = "0"
end   = "5"


[[cars]]
speed = 0.02
start = "1"
end   = "0"

[[cars]]
speed = 0.03
start = "1"
end   = "0"

[[cars]]
speed = 0.04
start = "1"
end   = "0"

[[cars]]
speed = 0.02
start = "2"
end   = "1"

[[cars]]
speed = 0.03
start = "2"
end   = "1"

[[cars]]
speed = 0.04
start = "2"
end   = "1"


[[cars]]
speed = 0.02
start = "3"
end   = "2"

[[cars]]
speed = 0.03
start = "3"
end   = "2"

[[cars]]
speed = 0.04
start = "3"
end   = "2"


[[cars]]
speed = 0.02
start = "4"
end   = "3"

[[cars]]
speed = 0.03
start = "4"
end   = "3"

[[cars]]
speed = 0.04
start = "4"
end   = "3"


[[cars]]
speed = 0.02
start = "5"
end   = "4"

[[cars]]
speed = 0.03
start = "5"
end   = "4"

[[cars]]
speed = 0.04
start = "5"
end   = "4"

