intersections = [
    "davis", 
    "porter", 
    "harvard",
    "central"
]

roads = [ 
    ["davis",   "porter"],
    ["porter", "harvard"],
    ["harvard", "central"],

    ["harvard", "porter"],
    ["porter", "davis"]
]

[[cars]]
speed = 0.02
start = "harvard"
end   = "davis"

[[cars]]
speed = 0.04
start = "davis"
end   = "harvard"

[[cars]]
speed = 0.08
start = "davis"
end   = "central"
